print("1. Python program to check if a string is palindrome or not")
print("2. Python program to check whether the string is Symmetrical or Palindrome")
print("3. Reverse words in a given String in Python")
print("4. Ways to remove i’th character from string in Python")
print("5. Python | Check if a Substring is Present in a Given String")
print("6. Python – Words Frequency in String Shorthands")
print("7. Python – Convert Snake case to Pascal case")
print("8. Find length of a string in python (4 ways)")
print("9. Python program to print even length words in a string")
print("10. Python program to accept the strings which contains all vowels")
print("11. Python | Count the Number of matching characters in a pair of string")
print("12. Remove all duplicates from a given string in Python")
print("13. Python – Least Frequent Character in String")
print("14. Python | Maximum frequency character in String")
print("15. Python | Program to check if a string contains any special character")
print("16. Generating random strings until a given string is generated")
print("17. Find words which are greater than given length k")
print("18. Python program for removing i-th character from a string")
print("19. Python program to split and join a string")
print("20. Python | Check if a given string is binary string or not")
print("21. Python program to find uncommon words from two Strings")
print("22. Python – Replace duplicate Occurrence in String")
print("23. Python – Replace multiple words with K")
print("24. Python | Permutation of a given string using inbuilt function")
print("25. Python | Check for URL in a String")
print("26. Execute a String of Code in Python")
print("27. String slicing in Python to rotate a string")
print("28. String slicing in Python to check if a string can become empty by recursive deletion")
print("29. Python Counter| Find all duplicate characters in string")
print("30. Python – Replace all occurrences of a substring in a string")